sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t clevins/docker-fib-project -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true clevins/docker-fib-project npm run test

after_success:
  - docker build -t clevins/fib-project-client ./client
  - docker build -t clevins/fib-project-nginx ./nginx
  - docker build -t clevins/fib-project-server ./server
  - docker build -t clevins/fib-project-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push clevins/fib-project-client
  - docker push clevins/fib-project-nginx
  - docker push clevins/fib-project-server
  - docker push clevins/fib-project-worker
