version: '3'
services: 
    postgres:
        image: postgres:latest
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    redis:
        image: redis
    
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        env_file: .env
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PGUSER=${PGUSER}
            - PGHOST=${PGHOST}
            - PGDATABASE=${PGDATABASE}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGPORT=${PGPORT}
    
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        tty: true

    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on:
            - api
            - client
        ports: 
            - '3005:80'
    
    